# Generated by Django 5.0 on 2024-01-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_register_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='dob',
        ),
    ]
